project:
  type: website
  output-dir: docs   # ðŸ”‘ GitHub Pages will use /docs

website:
  title: "dat303-blog"
  description: "A blog built with Quarto"
  site-url: https://richeder7.github.io/dat303-blog/
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Richeder7/dat303-blog

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
